### ISSUE TITLE
json_filter fails for Decimals

### ISSUE THREAD

**Issue by djpeach** [ej2/python-quickbooks#374]
The json_filter default for to_json (ToJsonMixin) fails with Decimals. I noticed this start happening when I upgraded from 0.9.3 -> 0.9.10, and found it to be related to the removal of simple_json. Not sure what happened, but I downgraded to 0.9.7 for now.

Here is the error I get:
```
AttributeError: 'decimal.Decimal' object has no attribute '__dict__'. Did you mean: '__dir__'?"
```

**Comment by ewilazarus** [comment]
I'm also seeing this error.

**Comment by ej2** [comment]
Should be fixed in `0.9.11`
